##############NETWORKS##############
networks:
  default:
    name: media
    external: true
##############NETWORKS##############

services:
#  bazarr: #subtitle grabber
#    image: ghcr.io/linuxserver/bazarr
#    container_name: bazarr
#    environment:
#      - PUID=$PUID
#      - PGID=$PGID
#      - TZ=$TZ
#    volumes:
#      - ./bazarr:/config
#      - $MEDIADIR/media/movies:/movies #optional
#      - $MEDIADIR/media/tv:/tv #optional
#    ports:
#      - 6767:6767
#    restart: unless-stopped

  jackett: #torrent download agent
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - ./jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped

  overseerr: #media requesting tool
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - ./overseerr:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped

  plex: # Media Server
    container_name: plex
    image: cr.hotio.dev/hotio/plex
    restart: unless-stopped
    logging:
      driver: json-file
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK=002
      - DEBUG=no
      - PLEX_CLAIM=$PLEX_CLAIM
      - PLEX_PASS=$PLEX_PASS
      - ADVERTISE_IP=$PLEX_ADVERTISE_IP
    volumes:
      - ./plex:/config:rw
      - $PLEXMEDIA:/data/media:rw
      - /tmp:/transcode:rw

    network_mode: host

  radarr: #movie search agent
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK=022
    volumes:
      - ./radarrV2:/config
      - $MEDIADIR:/data
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr: #TV show search agent
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK=022
    volumes:
      - ./sonarrV3:/config
      - $MEDIADIR:/data
    ports:
      - 8989:8989
    restart: unless-stopped


  # transmission-openvpn: #torrent download agent with vpn
  #   image: haugene/transmission-openvpn
  #   container_name: transmission-openvpn
  #   cap_add:
  #       - NET_ADMIN
  #   volumes:
  #       - ./transmission-openvpn:/config
  #       - $MEDIADIR/torrents:/data
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=$TZ
  #     - OPENVPN_PROVIDER=PIA
  #     - OPENVPN_CONFIG=spain,france,sweden,austria,italy,belgium,portugal
  #     - OPENVPN_USERNAME=$VPN_USR
  #     - OPENVPN_PASSWORD=$VPN_PWD
  #     - LOCAL_NETWORK=192.168.1.0/24
  #     - TRANSMISSION_WEB_UI=flood-for-transmission
  #     - GLOBAL_APPLY_PERMISSIONS=false
  #     - UMASK=022
  #   logging:
  #       driver: json-file
  #       options:
  #           max-size: 10m
  #   ports:
  #       - 9091:9091
  #   restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun-vpn
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=$VPNPROVIDER
      - OPENVPN_USER=$GTUSER
      - OPENVPN_PASSWORD=$GTPW
      - SERVER_REGIONS=$GTREGION
    ports:
    #the container port(s) should be the ones needed for the container you want to use the gluetun network
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - WEBUI_PORT=8080
    volumes:
      - ./qbit:/config
      - $MEDIADIR/downloads:/downloads
#    ports:
#      - 8080:8080
#      - 6881:6881
#      - 6881:6881/udp
    network_mode: service:gluetun
    restart: unless-stopped
